version: 2

sources:
  - name: input_data
    database: '{{ target.catalog }}'
    schema: source
    tables:
      - name: fact_sales  
      - name: fact_returns
      - name: dim_date
      - name: dim_store
      - name: dim_product
      - name: dim_customer
      
      - name: items